
import java.awt.Image;
import java.awt.Toolkit;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author syahm
 */
public class Calculator1 extends javax.swing.JFrame {

    /**
     * Creates new form Calculator1
     */
    
    double NumEnter1;
     double NumEnter2;
      double Result;
      String op;
    public Calculator1() {
        initComponents();
         Image icon = Toolkit.getDefaultToolkit().getImage("C:\\Users\\syahm\\Downloads\\Green-check-mark-icon.png");
    this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton19 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        textField1 = new java.awt.TextField();
        scrollbar1 = new java.awt.Scrollbar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtResult = new javax.swing.JTextPane();
        jbtnBS = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jbtnCE = new javax.swing.JButton();
        jbtnPM = new javax.swing.JButton();
        jbtnPlus = new javax.swing.JButton();
        jbtnDigit7 = new javax.swing.JButton();
        jbtnDigit9 = new javax.swing.JButton();
        jbtnDigit4 = new javax.swing.JButton();
        jbtnDigit5 = new javax.swing.JButton();
        jbtnSub = new javax.swing.JButton();
        jbtnDigit1 = new javax.swing.JButton();
        jbtnDigit2 = new javax.swing.JButton();
        jbtnMult = new javax.swing.JButton();
        jbtndiv = new javax.swing.JButton();
        jbtnDigit0 = new javax.swing.JButton();
        jbtnDot = new javax.swing.JButton();
        jbtnDigit6 = new javax.swing.JButton();
        jbtnDigit3 = new javax.swing.JButton();
        jbtnEqual = new javax.swing.JButton();
        jbtnDigit8 = new javax.swing.JButton();

        jButton19.setText("jButton1");

        jButton10.setText("jButton1");

        jButton11.setText("jButton1");

        jButton12.setText("jButton1");

        textField1.setText("textField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jtxtResult.setBackground(new java.awt.Color(204, 204, 204));
        jtxtResult.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jScrollPane1.setViewportView(jtxtResult);

        jbtnBS.setBackground(new java.awt.Color(153, 255, 255));
        jbtnBS.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnBS.setText("<=");
        jbtnBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBSActionPerformed(evt);
            }
        });

        jbtnC.setBackground(new java.awt.Color(153, 255, 255));
        jbtnC.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnC.setText("C");
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });

        jbtnCE.setBackground(new java.awt.Color(153, 255, 255));
        jbtnCE.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnCE.setText("CE");
        jbtnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCEActionPerformed(evt);
            }
        });

        jbtnPM.setBackground(new java.awt.Color(153, 255, 255));
        jbtnPM.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnPM.setText("±");
        jbtnPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPMActionPerformed(evt);
            }
        });

        jbtnPlus.setBackground(new java.awt.Color(153, 255, 255));
        jbtnPlus.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnPlus.setText("+");
        jbtnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPlusActionPerformed(evt);
            }
        });

        jbtnDigit7.setBackground(new java.awt.Color(153, 255, 255));
        jbtnDigit7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnDigit7.setText("7");
        jbtnDigit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit7ActionPerformed(evt);
            }
        });

        jbtnDigit9.setBackground(new java.awt.Color(153, 255, 255));
        jbtnDigit9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnDigit9.setText("9");
        jbtnDigit9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit9ActionPerformed(evt);
            }
        });

        jbtnDigit4.setBackground(new java.awt.Color(153, 255, 255));
        jbtnDigit4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnDigit4.setText("4");
        jbtnDigit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit4ActionPerformed(evt);
            }
        });

        jbtnDigit5.setBackground(new java.awt.Color(153, 255, 255));
        jbtnDigit5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnDigit5.setText("5");
        jbtnDigit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit5ActionPerformed(evt);
            }
        });

        jbtnSub.setBackground(new java.awt.Color(153, 255, 255));
        jbtnSub.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnSub.setText("-");
        jbtnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSubActionPerformed(evt);
            }
        });

        jbtnDigit1.setBackground(new java.awt.Color(153, 255, 255));
        jbtnDigit1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnDigit1.setText("1");
        jbtnDigit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit1ActionPerformed(evt);
            }
        });

        jbtnDigit2.setBackground(new java.awt.Color(153, 255, 255));
        jbtnDigit2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnDigit2.setText("2");
        jbtnDigit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit2ActionPerformed(evt);
            }
        });

        jbtnMult.setBackground(new java.awt.Color(153, 255, 255));
        jbtnMult.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnMult.setText("*");
        jbtnMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMultActionPerformed(evt);
            }
        });

        jbtndiv.setBackground(new java.awt.Color(153, 255, 255));
        jbtndiv.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtndiv.setText("÷");
        jbtndiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndivActionPerformed(evt);
            }
        });

        jbtnDigit0.setBackground(new java.awt.Color(153, 255, 255));
        jbtnDigit0.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jbtnDigit0.setText("0");
        jbtnDigit0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit0ActionPerformed(evt);
            }
        });

        jbtnDot.setBackground(new java.awt.Color(153, 255, 255));
        jbtnDot.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnDot.setText(".");
        jbtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDotActionPerformed(evt);
            }
        });

        jbtnDigit6.setBackground(new java.awt.Color(153, 255, 255));
        jbtnDigit6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnDigit6.setText("6");
        jbtnDigit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit6ActionPerformed(evt);
            }
        });

        jbtnDigit3.setBackground(new java.awt.Color(153, 255, 255));
        jbtnDigit3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnDigit3.setText("3");
        jbtnDigit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit3ActionPerformed(evt);
            }
        });

        jbtnEqual.setBackground(new java.awt.Color(153, 255, 255));
        jbtnEqual.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnEqual.setText("=");
        jbtnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEqualActionPerformed(evt);
            }
        });

        jbtnDigit8.setBackground(new java.awt.Color(153, 255, 255));
        jbtnDigit8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnDigit8.setText("8");
        jbtnDigit8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDigit8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnDigit1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(jbtnDigit0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnDigit2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnDigit3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnMult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtndiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnC, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnPM, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnBS, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(jbtnDigit7, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(jbtnDigit4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnDigit8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnDigit5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnDigit9, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(jbtnDigit6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnPlus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnBS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnC, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnPM, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDigit8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDigit7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDigit9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDigit4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDigit5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSub, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDigit6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDigit1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDigit2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnMult, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDigit3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDigit0, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtndiv, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPMActionPerformed
        
        double nums = Double.parseDouble(String.valueOf(jtxtResult.getText()));
        nums = nums * (-1);
        jtxtResult.setText(String.valueOf( nums));
    }//GEN-LAST:event_jbtnPMActionPerformed

    private void jbtnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPlusActionPerformed
        NumEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        op ="+";
    }//GEN-LAST:event_jbtnPlusActionPerformed

    private void jbtnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSubActionPerformed
        NumEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        op ="-";
    }//GEN-LAST:event_jbtnSubActionPerformed

    private void jbtnMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMultActionPerformed
        NumEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        op ="*";
    }//GEN-LAST:event_jbtnMultActionPerformed

    private void jbtnBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBSActionPerformed
        
        String backSp = null;
        
        if (jtxtResult.getText().length() > 0){ 
    }//GEN-LAST:event_jbtnBSActionPerformed
           StringBuilder sb = new StringBuilder(jtxtResult.getText());
           sb.deleteCharAt(jtxtResult.getText().length() - 1);
           backSp =sb.toString();
           jtxtResult.setText(backSp);
    }
    private void jbtndivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndivActionPerformed
        NumEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        op ="/";
    }//GEN-LAST:event_jbtndivActionPerformed

    private void jbtnDigit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit1ActionPerformed
        EnterNumbers("1");
    }//GEN-LAST:event_jbtnDigit1ActionPerformed

    private void jbtnDigit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit2ActionPerformed
        EnterNumbers("2");
    }//GEN-LAST:event_jbtnDigit2ActionPerformed

    private void jbtnDigit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit3ActionPerformed
        EnterNumbers("3");
    }//GEN-LAST:event_jbtnDigit3ActionPerformed

    private void jbtnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEqualActionPerformed
        NumEnter2 = Double.parseDouble(jtxtResult.getText());
        String equation = NumEnter1 + "" + op + "" + NumEnter2 + "=";
        if (op == "+")
        {
            Result = NumEnter1 + NumEnter2;
            jtxtResult.setText(equation + String.valueOf(Result));
        }
        
        else if (op == "-")
        {
            Result = NumEnter1 - NumEnter2;
            jtxtResult.setText(equation + String.valueOf(Result));
        }    
        else if (op == "*")
        {
            Result = NumEnter1 * NumEnter2;
            jtxtResult.setText(equation + String.valueOf(Result));
        }       
         else if (op == "/")
        {
            Result = NumEnter1 / NumEnter2;
            jtxtResult.setText(equation + String.valueOf(Result));
    }//GEN-LAST:event_jbtnEqualActionPerformed
        {
        }
        }
            
    private void jbtnDigit8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit8ActionPerformed
        EnterNumbers("8");
    }//GEN-LAST:event_jbtnDigit8ActionPerformed

    private void jbtnDigit9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit9ActionPerformed
        EnterNumbers("9");
    }//GEN-LAST:event_jbtnDigit9ActionPerformed

    private void jbtnDigit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit4ActionPerformed
        EnterNumbers("4");
    }//GEN-LAST:event_jbtnDigit4ActionPerformed

    private void jbtnDigit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit5ActionPerformed
        EnterNumbers("5");
    }//GEN-LAST:event_jbtnDigit5ActionPerformed

    private void jbtnDigit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit6ActionPerformed
        EnterNumbers("6");
    }//GEN-LAST:event_jbtnDigit6ActionPerformed

    private void jbtnDigit0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit0ActionPerformed
        EnterNumbers("0");
    }//GEN-LAST:event_jbtnDigit0ActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        jtxtResult.setText("");
       
    }//GEN-LAST:event_jbtnCActionPerformed

    private void jbtnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCEActionPerformed
        jtxtResult.setText("");
        
        String Fn, Sn;
        
        Fn = String.valueOf(NumEnter1);
        Sn = String.valueOf(NumEnter2);
        
        Fn ="";
        Sn ="";
        
    }//GEN-LAST:event_jbtnCEActionPerformed

    private void jbtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDotActionPerformed
        
        if (! jtxtResult.getText().contains("."));
        {
            jtxtResult.setText(jtxtResult.getText() + jbtnDot.getText());
        }
    }//GEN-LAST:event_jbtnDotActionPerformed

    private void jbtnDigit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDigit7ActionPerformed
        EnterNumbers("7");
    }//GEN-LAST:event_jbtnDigit7ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void EnterNumbers(String q)
    {
    
        String Nums = jtxtResult.getText() + q;
        jtxtResult.setText(Nums);
    }


public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton19;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnBS;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnCE;
    private javax.swing.JButton jbtnDigit0;
    private javax.swing.JButton jbtnDigit1;
    private javax.swing.JButton jbtnDigit2;
    private javax.swing.JButton jbtnDigit3;
    private javax.swing.JButton jbtnDigit4;
    private javax.swing.JButton jbtnDigit5;
    private javax.swing.JButton jbtnDigit6;
    private javax.swing.JButton jbtnDigit7;
    private javax.swing.JButton jbtnDigit8;
    private javax.swing.JButton jbtnDigit9;
    private javax.swing.JButton jbtnDot;
    private javax.swing.JButton jbtnEqual;
    private javax.swing.JButton jbtnMult;
    private javax.swing.JButton jbtnPM;
    private javax.swing.JButton jbtnPlus;
    private javax.swing.JButton jbtnSub;
    private javax.swing.JButton jbtndiv;
    private javax.swing.JTextPane jtxtResult;
    private java.awt.Scrollbar scrollbar1;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}


import java.awt.EventQueue;
import java.awt.Font;

import javax.swing.JFrame;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JMenu;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Properties;
import javax.swing.ImageIcon;
import javax.swing.JButton;

public class ArithmeticOperation {

	private JFrame frame;
	private JTextField textField;

	double num1 = 0;
	double num2 = 0;
	double result = 0;
	int num3 = 0;
	int num4 = 0;
	String operations;
	String answer;

	public static void main(String[] args) {
		try {
			UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
		} catch (Throwable e) {
			e.printStackTrace();
		}
		try {
		} catch (Throwable e) {
			e.printStackTrace();
		}
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					Properties props = new Properties();
					props.put("logoString", "Calculator");
					SmartLookAndFeel.setCurrentTheme(props);
					UIManager.setLookAndFeel(UIManager.getLookAndFeel());
					UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
					calculator window = new calculator();
					
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	public ArithmeticOperation() {
		initialize();
	}

	static long factorial(long ops) {
		long factor = 1;
		long i = 1;
		while (i <= ops) {
			factor *= i;
			i++;
		}
		return factor;
	}

	private void initialize() {

		frame = new JFrame();
		frame.setBounds(450, 150, 220, 323);
		frame.setResizable(false);
		frame.setTitle("Standard Calculator");
		ImageIcon img = new ImageIcon("resources/calculator.png");
		frame.setIconImage(img.getImage());
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.getContentPane().setLayout(null);
		frame.setLocationRelativeTo(null);

		textField = new JTextField(20);
		textField.setBounds(6, 24, 202, 44);
		textField.setHorizontalAlignment(SwingConstants.RIGHT);
		textField.setFont(new Font("Tahoma", Font.BOLD, 30));
		textField.setEditable(false);
		textField.setColumns(10);
		frame.getContentPane().add(textField);

		JMenuBar menuBar = new JMenuBar();
		menuBar.setBounds(0, 0, 230, 23);
		frame.getContentPane().add(menuBar);

		JMenu mnNewMenu = new JMenu("View");
		menuBar.add(mnNewMenu);

		JMenuItem standard = new JMenuItem("Standard Calculator");
		JMenuItem scientific = new JMenuItem("Scientific Calculator");

		standard.setEnabled(false);

		standard.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				frame.setBounds(450, 150, 220, 323);
				frame.setResizable(false);
				frame.setTitle("Standard Calculator");
				frame.setLocationRelativeTo(null);

				menuBar.setBounds(0, 0, 220, 23);

				standard.setEnabled(false);
				scientific.setEnabled(true);

				textField.setBounds(6, 24, 202, 45);
				textField.setHorizontalAlignment(SwingConstants.RIGHT);
				textField.setColumns(10);

				textField.setText("");
			}
		});
		mnNewMenu.add(standard);

		scientific.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				frame.setBounds(450, 150, 440, 327);
				frame.setResizable(false);
				frame.setTitle("Scientific Calculator");
				frame.setLocationRelativeTo(null);

				menuBar.setBounds(0, 0, 440, 23);

				scientific.setEnabled(false);
				standard.setEnabled(true);

				textField.setBounds(6, 24, 422, 45);
				textField.setHorizontalAlignment(SwingConstants.RIGHT);
				textField.setColumns(10);

				textField.setText("");
			}
		});

		mnNewMenu.add(scientific);

		JMenuItem about = new JMenuItem("About");
		about.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				JOptionPane.showMessageDialog(null, "Scientific Calculator using Java Swing by Avishek Das");
			}
		});

		mnNewMenu.add(about);

		JMenuItem exit = new JMenuItem("Exit");
		exit.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				System.exit(0);
			}
		});
		mnNewMenu.add(exit);

		JButton bs = new JButton("\u232b");
		bs.setBounds(6, 90, 50, 35);
		bs.setFont(new Font("SansSerif", Font.PLAIN, 10));
		frame.getContentPane().add(bs);
		bs.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				String backspace = null;
				if (textField.getText().length() > 0) {
					StringBuilder strB = new StringBuilder(textField.getText());
					strB.deleteCharAt(textField.getText().length() - 1);
					backspace = strB.toString();
					textField.setText(backspace);

				}
			}
		});

		JButton clear = new JButton("C");
		clear.setBounds(56, 90, 50, 35);
		frame.getContentPane().add(clear);
		clear.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				textField.setText("");

			}
		});

		JButton perc = new JButton("%");
		perc.setBounds(107, 90, 50, 35);
		frame.getContentPane().add(perc);
		perc.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				if (textField.getText().isEmpty()) {
					JOptionPane.showMessageDialog(null, "Please make a operation first");
				}
				if (textField.getText().length() >= 1) {
					num1 = Double.parseDouble(textField.getText());
					textField.setText("");
					operations = "%";
				}
			}
		});

		JButton sum = new JButton("+");
		sum.setBounds(158, 90, 50, 35);
		frame.getContentPane().add(sum);
		sum.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				if (textField.getText().isEmpty()) {
					JOptionPane.showMessageDialog(null, "Please make a operation first");
				}
				if (textField.getText().length() >= 1) {
					num1 = Double.parseDouble(textField.getText());
					textField.setText("");
					operations = "+";
				}
			}

		});

		JButton seven = new JButton("7");
		seven.setBounds(6, 130, 50, 35);
		frame.getContentPane().add(seven);
		seven.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				String iNum = textField.getText() + seven.getText();
				textField.setText(iNum);

			}
		});

		JButton eight = new JButton("8");
		eight.setBounds(56, 130, 50, 35);
		frame.getContentPane().add(eight);
		eight.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				String iNum = textField.getText() + eight.getText();
				textField.setText(iNum);

			}
		});

		JButton nine = new JButton("9");
		nine.setBounds(107, 130, 50, 35);
		frame.getContentPane().add(nine);
		nine.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				String iNum = textField.getText() + nine.getText();
				textField.setText(iNum);

			}
		});

		JButton sub = new JButton("-");
		sub.setBounds(158, 130, 50, 35);
		frame.getContentPane().add(sub);
		sub.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				if (textField.getText().isEmpty()) {
					JOptionPane.showMessageDialog(null, "Please make a operation first");
				}
				if (textField.getText().length() >= 1) {
					num1 = Double.parseDouble(textField.getText());
					textField.setText("");
					operations = "-";
				}
			}
		});

		JButton four = new JButton("4");
		four.setBounds(6, 170, 50, 35);
		frame.getContentPane().add(four);
		four.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				String iNum = textField.getText() + four.getText();
				textField.setText(iNum);

			}
		});

		JButton five = new JButton("5");
		five.setBounds(56, 170, 50, 35);
		frame.getContentPane().add(five);
		five.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				String iNum = textField.getText() + five.getText();
				textField.setText(iNum);

			}
		});

		JButton six = new JButton("6");
		six.setBounds(107, 170, 50, 35);
		frame.getContentPane().add(six);
		six.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				String iNum = textField.getText() + six.getText();
				textField.setText(iNum);

			}
		});

		JButton mul = new JButton("*");
		mul.setBounds(158, 170, 50, 35);
		frame.getContentPane().add(mul);
		mul.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				if (textField.getText().isEmpty()) {
					JOptionPane.showMessageDialog(null, "Please make a operation first");
				}
				if (textField.getText().length() >= 1) {
					num1 = Double.parseDouble(textField.getText());
					textField.setText("");
					operations = "*";
				}
			}
		});

		JButton one = new JButton("1");
		one.setBounds(6, 210, 50, 35);
		frame.getContentPane().add(one);
		one.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				String iNum = textField.getText() + one.getText();
				textField.setText(iNum);

			}
		});

		JButton two = new JButton("2");
		two.setBounds(56, 210, 50, 35);
		frame.getContentPane().add(two);
		two.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				String iNum = textField.getText() + two.getText();
				textField.setText(iNum);

			}
		});

		JButton three = new JButton("3");
		three.setBounds(107, 210, 50, 35);
		frame.getContentPane().add(three);
		three.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				String iNum = textField.getText() + three.getText();
				textField.setText(iNum);

			}
		});

		JButton div = new JButton("/");
		div.setBounds(158, 210, 50, 35);
		frame.getContentPane().add(div);
		div.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				if (textField.getText().isEmpty()) {
					JOptionPane.showMessageDialog(null, "Please make a operation first");
				}
				if (textField.getText().length() >= 1) {
					num1 = Double.parseDouble(textField.getText());
					textField.setText("");
					operations = "/";
				}
			}
		});

		JButton zero = new JButton("0");
		zero.setBounds(6, 250, 50, 35);
		frame.getContentPane().add(zero);
		zero.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				String iNum = textField.getText() + zero.getText();
				textField.setText(iNum);

			}
		});

		JButton dot = new JButton(".");
		dot.setBounds(56, 250, 50, 35);
		frame.getContentPane().add(dot);
		dot.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				if (!textField.getText().contains(".")) {
					String iNum = textField.getText() + dot.getText();
					textField.setText(iNum);

				}
			}
		});

		JButton pm = new JButton("\u00B1");
		pm.setBounds(107, 250, 50, 35);
		frame.getContentPane().add(pm);
		pm.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (textField.getText().isEmpty()) {
					JOptionPane.showMessageDialog(null, "Please make a operation first");
				}
				if (textField.getText().length() >= 1) {
					double ops = Double.parseDouble(textField.getText());
					ops = ops * (-1);
					textField.setText(String.valueOf(ops));
				}
			}
		});

		JButton resc = new JButton("1/x");
		resc.setBounds(224, 90, 50, 35);
		frame.getContentPane().add(resc);
		resc.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				double ops = Double.parseDouble(textField.getText());
				if (ops == 0) {
					JOptionPane.showMessageDialog(null, "Cannot be divided by 0");
					textField.setText("");
				} else if (textField.getText().isEmpty()) {
					JOptionPane.showMessageDialog(null, "Please enter a number");
				} else {
					ops = 1 / ops;
					textField.setText(String.valueOf(ops));
				}
			}
		});

		JButton sin = new JButton("sin");
		sin.setBounds(275, 90, 50, 35);
		frame.getContentPane().add(sin);
		sin.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent e) {
				if (textField.getText().isEmpty()) {
					JOptionPane.showMessageDialog(null, "Please enter a number");
				}
				if (textField.getText().length() >= 1) {
					double ops = Math.toRadians(Double.parseDouble(textField.getText()));
					ops = Math.sin(Math.toDegrees(ops));
					textField.setText(String.valueOf(ops));
				}

			}
		});

		JButton cos = new JButton("cos");
		cos.setBounds(327, 90, 50, 35);
		frame.getContentPane().add(cos);
		cos.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				if (textField.getText().isEmpty()) {
					JOptionPane.showMessageDialog(null, "Please enter a number");
				}
				if (textField.getText().length() >= 1) {
					double ops = Math.toRadians(Double.parseDouble(textField.getText()));
					ops = Math.cos(ops);
					textField.setText(String.valueOf(ops));
				}
			}
		});

		JButton tan = new JButton("tan");
		tan.setBounds(379, 90, 50, 35);
		frame.getContentPane().add(tan);
		tan.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				if (textField.getText().isEmpty()) {
					JOptionPane.showMessageDialog(null, "Please enter a number");
				}
				if (textField.getText().length() >= 1) {
					double ops = Math.toRadians(Double.parseDouble(textField.getText()));
					ops = Math.tan(ops);
					textField.setText(String.valueOf(ops));
				}
			}
		});

		JButton square = new JButton("x^2");
		square.setBounds(224, 130, 50, 35);
		frame.getContentPane().add(square);
		square.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				if (textField.getText().isEmpty()) {
					JOptionPane.showMessageDialog(null, "Please enter a number");
				}
				if (textField.getText().length() >= 1) {
					double ops = Double.parseDouble(textField.getText());
					ops = Math.pow(ops, 2);
					textField.setText(String.valueOf(ops));
				}
			}
		});

		JButton sqrt = new JButton("\u221A");
		sqrt.setBounds(275, 130, 50, 35);
		frame.getContentPane().add(sqrt);
		sqrt.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				if (textField.getText().isEmpty()) {
					JOptionPane.showMessageDialog(null, "Please enter a number");
				}
				if (textField.getText().length() >= 1) {
					double ops = Double.parseDouble(textField.getText());
					ops = Math.sqrt(ops);
					textField.setText(String.valueOf(ops));
				}
			}
		});

		JButton fact = new JButton("n!");
		fact.setBounds(327, 130, 50, 35);
		frame.getContentPane().add(fact);
		fact.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				long ops = Integer.parseInt(textField.getText());
				if (textField.getText().equals("1") || textField.getText().equals("0")) {
					textField.setText("1");
				}
				else if(ops>=21)
				{
					JOptionPane.showMessageDialog(null, "Please enter a number from 1 to 20","Error",JOptionPane.ERROR_MESSAGE);
					textField.setText("");
				}

				else {
					long fac = factorial(ops);
					textField.setText("");
					textField.setText(String.valueOf(fac));
				}
			}
		});

		JButton mod = new JButton("Mod");
		mod.setBounds(379, 130, 50, 35);
		frame.getContentPane().add(mod);
		mod.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				if (textField.getText().isEmpty()) {
					JOptionPane.showMessageDialog(null, "Please make a operation first");
				}
				if (textField.getText().length() >= 1) {
					num1 = Double.parseDouble(textField.getText());
					textField.setText("");
					operations = "mod";
				}
			}
		});

		JButton cube = new JButton("x^3");
		cube.setBounds(224, 170, 50, 35);
		frame.getContentPane().add(cube);
		cube.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				if (textField.getText().isEmpty()) {
					JOptionPane.showMessageDialog(null, "Please enter a number");
				}
				if (textField.getText().length() >= 1) {
					double ops = Double.parseDouble(textField.getText());
					ops = Math.pow(ops, 3);
					textField.setText(String.valueOf(ops));
				}
			}
		});

		JButton cbrt = new JButton("\u221B");
		cbrt.setBounds(275, 170, 50, 35);
		frame.getContentPane().add(cbrt);
		cbrt.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (textField.getText().isEmpty()) {
					JOptionPane.showMessageDialog(null, "Please enter a number");
				}
				if (textField.getText().length() >= 1) {
					double ops = Double.parseDouble(textField.getText());
					ops = Math.cbrt(ops);
					textField.setText(String.valueOf(ops));
				}
			}
		});

		JButton log = new JButton("log");
		log.setBounds(327, 170, 50, 35);
		frame.getContentPane().add(log);
		log.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				if (textField.getText().isEmpty()) {
					JOptionPane.showMessageDialog(null, "Please enter a number");
				} else {
					double ops = Double.parseDouble(textField.getText());
					ops = Math.log10(ops);
					textField.setText(String.valueOf(ops));
				}
			}
		});

		JButton bin = new JButton("Bin");
		bin.setBounds(379, 170, 50, 35);
		frame.getContentPane().add(bin);
		bin.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				if (textField.getText().isEmpty()) {
					JOptionPane.showMessageDialog(null, "Please enter a number");
				} else {
					int a = Integer.parseInt(textField.getText());
					textField.setText(Integer.toBinaryString(a));
					// textField.setText(Integer.toString(a,2)); //another method
				}
			}
		});

		JButton power = new JButton("x^y");
		power.setBounds(224, 210, 50, 35);
		frame.getContentPane().add(power);
		power.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (textField.getText().isEmpty()) {
					JOptionPane.showMessageDialog(null, "Please make a operation first");
				}
				if (textField.getText().length() >= 1) {
					num1 = Double.parseDouble(textField.getText());
					textField.setText("");
					operations = "power";
				}
			}
		});

		JButton root = new JButton("y\u221Ax");
		root.setBounds(275, 210, 50, 35);
		frame.getContentPane().add(root);
		root.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				if (textField.getText().isEmpty()) {
					JOptionPane.showMessageDialog(null, "Please make a operation first");
				}
				if (textField.getText().length() >= 1) {
					num1 = Double.parseDouble(textField.getText());
					textField.setText("");
					operations = "root";
				}
			}
		});

		JButton ln = new JButton("ln");
		ln.setBounds(327, 210, 50, 35);
		frame.getContentPane().add(ln);
		ln.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				if (textField.getText().isEmpty()) {
					JOptionPane.showMessageDialog(null, "Please make a operation first");
				} else {
					double ops = Double.parseDouble(textField.getText());
					ops = Math.log(ops);
					textField.setText(String.valueOf(ops));
				}
			}
		});

		JButton oct = new JButton("Oct");
		oct.setBounds(379, 210, 50, 35);
		frame.getContentPane().add(oct);
		oct.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				if (textField.getText().isEmpty()) {
					JOptionPane.showMessageDialog(null, "Please make a operation first");
				} else {
					int a = Integer.parseInt(textField.getText());
					textField.setText("");
					textField.setText(Integer.toOctalString(a));
					// textField.setText(Integer.toString(a,8)); //another method
				}
			}

		});

		JButton tenpow = new JButton("10^x");
		tenpow.setBounds(224, 250, 50, 35);
		frame.getContentPane().add(tenpow);
		tenpow.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				if (textField.getText().isEmpty()) {
					JOptionPane.showMessageDialog(null, "Please enter a number");
				} else {
					double ops = Double.parseDouble(textField.getText());
					ops = Math.pow(10, ops);
					textField.setText(String.valueOf(ops));
				}
			}
		});

		JButton exp = new JButton("e^x");
		exp.setBounds(275, 250, 50, 35);
		frame.getContentPane().add(exp);
		exp.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				if (textField.getText().isEmpty()) {
					JOptionPane.showMessageDialog(null, "Please enter a number");
				} else {
					double ops = Double.parseDouble(textField.getText());
					ops = Math.exp(ops);
					textField.setText(String.valueOf(ops));
				}
			}
		});

		JButton pi = new JButton("\u03C0");
		pi.setBounds(327, 250, 50, 35);
		frame.getContentPane().add(pi);
		pi.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				double ops;
				ops = Math.PI;
				textField.setText(String.valueOf(ops));
			}
		});

		JButton hex = new JButton("Hex");
		hex.setBounds(379, 250, 50, 35);
		frame.getContentPane().add(hex);
		hex.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				if (textField.getText().isEmpty()) {
					JOptionPane.showMessageDialog(null, "Please enter a number");
				} else {
					int a = Integer.parseInt(textField.getText());
					textField.setText(Integer.toHexString(a));
					// textField.setText(Integer.toString(a,16)); //another method
				}
			}
		});

		JButton equal = new JButton("=");
		equal.setBounds(158, 250, 50, 35);
		frame.getContentPane().add(equal);

		equal.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				num2 = Double.parseDouble(textField.getText());

				if (operations == "+") {

					result = num1 + num2;
					answer = String.format("%.2f", result);
					textField.setText(answer);

				}
				if (operations == "-") {
					result = num1 - num2;
					answer = String.format("%.2f", result);
					textField.setText(answer);
				}
				if (operations == "*") {
					result = num1 * num2;
					answer = String.format("%.2f", result);
					textField.setText(answer);
				}
				if (operations == "/") {
					if (num2 == 0) {
						JOptionPane.showMessageDialog(null, "Cannot be divided by 0");
						textField.setText("");
					} else {
						result = num1 / num2;
						answer = String.format("%.2f", result);
						textField.setText(answer);
					}
				}
				if (operations == "mod") {
					if (num2 == 0) {
						JOptionPane.showMessageDialog(null, "Cannot be divided by 0");
						textField.setText("");
					} else {
						result = num1 % num2;
						answer = String.format("%.2f", result);
						textField.setText(answer);
					}
				}
				if (operations == "power") {
					result = Math.pow(num1, num2);
					answer = String.format("%.2f", result);
					textField.setText(answer);
				}
				if (operations == "root") {
					if (num1 == 0) {
						JOptionPane.showMessageDialog(null, "Cannot be divided by 0");
						textField.setText("");
					} else {
						result = Math.pow(num1, 1 / num2);
						answer = String.format("%.2f", result);
						textField.setText(answer);
					}

				}
				if (operations == "%") {
					result = num1 * (num2 / 100);
					answer = String.format("%.2f", result);
					textField.setText(answer);
				}
			}
		});
	}

    private static class calculator {

        public calculator() {
        }

        private class frame {

                private static void setVisible(boolean b) {
                    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

            public frame() {
            }
        }
    }
}